using Microsoft.EntityFrameworkCore.Migrations;

namespace SIGSUC.DAL.Migrations
{
    public partial class DadosIniciais : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            #region Adicionando Continentes
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (1,'África')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (2,'África/Ásia')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (3,'América Central')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (4,'América do Norte')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (5,'América do Sul')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (6,'Ásia')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (7,'Ásia//Europa')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (8,'Ásia/Oceania')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (9,'Europa')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (10,'Europa/Ásia')");
            migrationBuilder.Sql("Insert into continentes (continenteid, descricao) values (11,'Oceania')");
            #endregion

            #region Adicionando países
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (756,'África do Sul','27',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (474,'Marrocos','212',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (685,'Saara Ocidental','212',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (59,'Argélia','213',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (820,'Tunísia','216',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (438,'Líbia','218',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (285,'Gambia','220',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (728,'Senegal','221',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (488,'Mauritânia','222',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (464,'Mali','223',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (329,'Guiné','224',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (193,'Costa do Marfim','225',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (31,'Burkina Faso','226',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (525,'Niger','227',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (800,'Togo','228',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (485,'Maurício','230',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (434,'Libéria','231',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (735,'Serra Leoa','232',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (289,'Gana','233',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (528,'Nigéria','234',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (640,'República Centro-Africana','236',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (145,'Camarões','237',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (788,'Chade','237',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (127,'Cabo Verde, República de','238',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (720,'São Tomé e Príncipe, Ilhas','239',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (331,'Guiné-Equatorial','240',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (281,'Gabão','241',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (177,'Congo','242',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (40,'Angola','244',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (334,'Guiné-Bissau','245',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (782,'Território Britânico no Oceano Índico','246',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (731,'Seychelles','248',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (759,'Sudão','249',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (675,'Ruanda','250',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (253,'Etiópia','251',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (748,'Somália','252',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (783,'Djibuti','253',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (623,'Quênia','254',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (780,'Tanzania, Rep. Unida da','255',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (833,'Uganda','256',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (115,'Burundi','257',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (505,'Moçambique','258',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (890,'Zâmbia','260',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (450,'Madagascar','261',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (660,'Reunião, Ilha','262',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (665,'Zimbabue','263',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (507,'Namíbia','264',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (458,'Malavi','265',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (426,'Lesoto','266',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (101,'Botsuana','267',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (754,'Suazilândia','268',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (173,'Comores, Ilhas','269',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (710,'Santa Helena','290',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (243,'Eritreia','291',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (240,'Egito','20',2)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (41,'Anguilla','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (43,'Antigua E Barbuda','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (77,'Bahamas, Ilhas','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (83,'Barbados','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (90,'Bermudas','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (137,'Cayman, Ilhas','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (235,'Dominica, Ilha','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (297,'Granada','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (391,'Jamaica','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (501,'Montserrat, Ilhas','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (611,'Porto Rico','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (647,'República Dominicana','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (695,'São Cristovão e Neves, Ilhas','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (705,'São Vicente e Granadinas','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (715,'Santa Lúcia','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (815,'Trinidad e Tobago','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (823,'Turcas e Caicos, Ilhas','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (863,'Virgens, Ilhas (Britânicas)','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (866,'Virgens, Ilhas (E.U.A.)','1',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (199,'Cuba','53',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (65,'Aruba','297',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (88,'Belize','501',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (317,'Guatemala','502',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (687,'El Salvador','503',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (345,'Honduras','504',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (521,'Nicarágua','505',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (196,'Costa Rica','506',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (580,'Panamá','507',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (341,'Haiti','509',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (309,'Guadalupe','590',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (477,'Martinica','596',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (47,'Antilhas Holandesas','599',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (149,'Canadá','1',4)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (249,'Estados Unidos','1',4)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (493,'México','52',4)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (305,'Groenlândia','299',4)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (700,'São Pedro e Miquelon','508',4)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (589,'Peru','51',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (63,'Argentina','54',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (105,'Brasil','55',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (158,'Chile','56',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (169,'Colômbia','57',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (850,'Venezuela','58',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (255,'Falkland (Ilhas Malvinas)','500',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (97,'Bolívia','591',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (337,'Guiana','592',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (239,'Equador','593',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (325,'Guiana Francesa','594',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (586,'Paraguai','595',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (770,'Suriname','597',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (845,'Uruguai','598',5)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (153,'Cazaquistao, República do','7',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (455,'Malásia','60',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (267,'Filipinas','63',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (741,'Cingapura','65',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (776,'Tailândia','66',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (399,'Japão','81',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (187,'Coréia, Rep.Pop.Democrática','82',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (858,'Vietnã','84',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (160,'China, República Popular','86',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (361,'Índia','91',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (576,'Paquistão','92',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (13,'Afeganistão','93',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (750,'Sri Lanka','94',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (93,'Mianmar (Birmânia)','95',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (372,'Irã, República Islâmica do','98',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (64,'Armênia, República da','374',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (795,'Timor Leste','670',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (108,'Brunei','673',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (190,'Coréia, República da','850',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (351,'Hong Kong','852',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (447,'Macau','853',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (141,'Camboja','855',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (420,'Laos, Rep.Pop.Democr.do','856',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (81,'Bangladesh','880',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (461,'Maldivas','960',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (431,'Líbano','961',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (403,'Jordânia','962',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (744,'Síria, República Árabe da','963',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (369,'Iraque','964',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (53,'Arábia Saudita','966',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (357,'Iemen','967',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (556,'Omã','968',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (998,'Delegação Especial da Palestina','970',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (244,'Emirados Árabes Unidos','971',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (383,'Israel','972',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (80,'Bahrein, Ilhas','973',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (154,'Catar','974',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (119,'Butão','975',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (497,'Mongólia','976',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (517,'Nepal','977',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (772,'Tadjiquistão, República do','992',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (824,'Turcomenistão, República do','993',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (73,'Azerbaijão, República do','994',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (291,'Geórgia, República da','995',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (625,'Quirguiz, República da','996',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (847,'Uzbequistão, República do','998',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (827,'Turquia','90',7)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (365,'Indonésia','62',8)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (301,'Grécia','30',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (573,'Países Baixos (Holanda)','31',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (87,'Bélgica','32',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (275,'França','33',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (245,'Espanha','34',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (355,'Hungria, República da','36',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (386,'Itália','39',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (670,'Romênia','40',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (767,'Suíça','41',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (72,'Áustria','43',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (628,'Reino Unido','44',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (232,'Dinamarca','45',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (764,'Suécia','46',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (538,'Noruega','47',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (603,'Polônia, República da','48',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (23,'Alemanha','49',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (259,'Feroe, Ilhas','298',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (293,'Gibraltar','350',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (607,'Portugal','351',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (445,'Luxemburgo','352',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (375,'Irlanda','353',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (379,'Islândia','354',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (17,'Albânia, República da','355',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (467,'Malta','356',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (163,'Chipre','357',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (271,'Finlândia','358',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (111,'Bulgária, República da','359',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (442,'Lituânia, República da','370',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (427,'Letônia, República da','371',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (251,'Estônia, República da','372',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (494,'Moldavia, República da','373',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (37,'Andorra','376',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (495,'Mônaco','377',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (697,'San Marino','378',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (848,'Vaticano, Est. da Cidade do','379',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (831,'Ucrânia','380',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (737,'Servia','381',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (498,'Montenegro','382',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (195,'Croácia, República da','385',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (246,'Eslovênia, República da','386',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (98,'Bosnia-Herzegovina (República da)','387',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (449,'Macedônia, Ant.Rep.Iugoslava','389',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (791,'Tcheca, República','420',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (247,'Eslovaca, República','421',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (440,'Liechtenstein','423',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (676,'Rússia, Federação da','7',10)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (472,'Marianas do Norte','1',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (691,'Samoa Americana','1',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (69,'Austrália','61',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (548,'Nova Zelândia','64',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (313,'Guam','671',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (165,'Cocos-Keeling, Ilhas','672',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (511,'Christmas,Ilhas (Navidad)','672',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (535,'Norfolk, Ilha','672',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (508,'Nauru','674',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (545,'Papua Nova Guiné','675',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (810,'Tonga','676',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (677,'Salomão, Ilhas','677',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (551,'Vanuatu','678',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (870,'Fiji','679',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (575,'Palau','680',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (875,'Wallis e Futuna, Ilhas','681',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (183,'Cook, Ilhas','682',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (531,'Niue, Ilha','683',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (690,'Samoa','685',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (411,'Kiribati','686',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (542,'Nova Caledônia','687',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (828,'Tuvalu','688',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (599,'Polinésia Francesa','689',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (805,'Toquelau, Ilhas','690',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (499,'Micronésia','691',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (476,'Marshall, Ilhas','692',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (888,'Congo, República Democrática do','243',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (85,'Belarus, República da','',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (150,'Jersey, Ilha do Canal','',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (151,'Canárias, Ilhas','',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (161,'Formosa (Taiwan)','',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (198,'Coveite (Kuwait)','965',6)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (229,'Benin','',1)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (359,'Man, Ilha de','',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (396,'Johnston, Ilhas','',4)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (423,'Lebuan, Ilhas','',4)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (452,'Madeira, Ilha da','',9)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (490,'Midway, Ilhas','',4)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (566,'Pacífico, Ilhas do  (possessão dos EUA)','',4)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (593,'Pitcairn, Ilha De','',11)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (678,'Saint Kitts e Nevis','',3)");
            migrationBuilder.Sql("insert into paises (paisId, nome,codigoarea,continenteid) values (873,'Wake, Ilha','',4)");
            #endregion

            #region Adicionando Regiões
            migrationBuilder.Sql("Insert into regioes (paisid, regiaoid, descricao) values (105,1,'Centro Oeste')");
            migrationBuilder.Sql("Insert into regioes (paisid, regiaoid, descricao) values (105,2,'Norte')");
            migrationBuilder.Sql("Insert into regioes (paisid, regiaoid, descricao) values (105,3,'Nordeste')");
            migrationBuilder.Sql("Insert into regioes (paisid, regiaoid, descricao) values (105,4,'Sudeste')");
            migrationBuilder.Sql("Insert into regioes (paisid, regiaoid, descricao) values (105,5,'Sul')");

            #endregion

            #region Adicionando Estados
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'GO','Goiás',1)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'MT','Mato Grosso',1)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'MS','Mato Grosso do Sul',1)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'DF','Distrito Federal',1)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'AM','Amazonas',2)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'AC','Acre',2)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'RO','Rondônia',2)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'RR','Roraima',2)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'AP','Amapá',2)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'TO','Tocantins',2)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'PA','Para',2)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'MA','Maranhão',3)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'PI','Piaui',3)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'CE','Ceara',3)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'RN','Rio Grande do Norte',3)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'PB','Paraiba',3)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'PE','Pernambuco',3)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'SE','Sergipe',3)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'AL','Alagoas',3)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'BA','Bahia',3)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'SP','São Paulo',4)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'MG','Minas Gerais',4)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'RJ','Rio de Janeiro',4)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'ES','Espirito Santo',4)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'PR','Parana',5)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'SC','Santa Catarina',5)");
            migrationBuilder.Sql("insert into ufs (paisid,siglaid,descricao,regiaoid) values (105,'RS','Rio Grande do Sul',5)");

            #endregion

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM UFS");
            migrationBuilder.Sql("DELETE FROM REGIOES");
            migrationBuilder.Sql("DELETE FROM PAISES");
            migrationBuilder.Sql("DELETE FROM CONTINENTES");

        }
    }
}
