// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGSUC.DAL.Context;

namespace SIGSUC.DAL.Migrations
{
    [DbContext(typeof(SIGSUCContext))]
    partial class SIGSUCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SIGSUC.Domain.Entities.Common.Continente", b =>
                {
                    b.Property<int>("ContinenteId");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("ContinenteId");

                    b.ToTable("Continentes");
                });

            modelBuilder.Entity("SIGSUC.Domain.Entities.Common.Pais", b =>
                {
                    b.Property<int>("PaisId");

                    b.Property<string>("CodigoArea")
                        .HasColumnType("varchar(4)");

                    b.Property<int>("ContinenteId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("PaisId");

                    b.HasIndex("ContinenteId");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("SIGSUC.Domain.Entities.Common.Regiao", b =>
                {
                    b.Property<int>("PaisId");

                    b.Property<int>("RegiaoId");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaisId", "RegiaoId");

                    b.ToTable("Regioes");
                });

            modelBuilder.Entity("SIGSUC.Domain.Entities.Common.UF", b =>
                {
                    b.Property<int>("PaisId");

                    b.Property<string>("SiglaId")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RegiaoId");

                    b.HasKey("PaisId", "SiglaId");

                    b.HasIndex("PaisId", "RegiaoId");

                    b.ToTable("UFs");
                });

            modelBuilder.Entity("SIGSUC.Domain.Entities.Common.Pais", b =>
                {
                    b.HasOne("SIGSUC.Domain.Entities.Common.Continente", "Continente")
                        .WithMany("Paises")
                        .HasForeignKey("ContinenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGSUC.Domain.Entities.Common.Regiao", b =>
                {
                    b.HasOne("SIGSUC.Domain.Entities.Common.Pais", "Pais")
                        .WithMany("Regioes")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGSUC.Domain.Entities.Common.UF", b =>
                {
                    b.HasOne("SIGSUC.Domain.Entities.Common.Pais", "Pais")
                        .WithMany("UFs")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGSUC.Domain.Entities.Common.Regiao", "Regiao")
                        .WithMany("UFs")
                        .HasForeignKey("PaisId", "RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
